version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore AwsPipelineDemo/AwsPipelineDemo.csproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet build AwsPipelineDemo/AwsPipelineDemo.csproj

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -o ./ AwsPipelineDemo/AwsPipelineDemo.csproj
      - |
        if [ "$BUILD_ENV" = "dev" ] ; then
          echo Configuring ebextensions with dev variables
          export $(cat .ebextensions/.env.dev | xargs)  
        else
          echo Configuring ebextensions with prod variables
          export $(cat .ebextensions/.env.prod | xargs)  
        fi
      - |
        echo Transforming ebextension config files
        for i in .ebextensions/*.config ; do
            envsubst < $i > $i+.temp
            mv $i+.temp $i
        done
        echo Successfully transformed ebextensions config values with $BUILD_ENV variables

artifacts:
  files:
    - '**/*'


- schedule a little bit of time to test this out (next week?)
- change .env.dev and .env.prod to be differnet file names (decide on a file name convention)
- change so we have a single if check on BUILD_ENV to see if it's dev and set, default it to go to prod environemnt
